include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: error
    unused_local_variable: error
    dead_code: error
    missing_return: error
    parameter_assignments: error
    avoid_print: warning
    avoid_dynamic_calls: warning
    always_declare_return_types: warning
    prefer_const_constructors: warning
    prefer_final_locals: warning

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - avoid_print
    - avoid_returning_null
    - avoid_returning_null_for_void
    - avoid_unnecessary_containers
    - constant_identifier_names
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - unnecessary_null_checks
    - use_key_in_widget_constructors
    - sized_box_for_whitespace
    - prefer_const_constructors_in_immutables
    - sort_child_properties_last
